services:
  app:
    image: ghcr.io/beeman/demo-stack-remix:latest
    ports:
      - "13000:13000"
    environment:
      PORT: 13000
      DATABASE_URL: postgresql://demo-stack-remix:demo-stack-remix@postgres:5432/demo-stack-remix?schema=public
    depends_on:
      - postgres
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: demo-stack-remix
      POSTGRES_USER: demo-stack-remix
      POSTGRES_PASSWORD: demo-stack-remix
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
