services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: demo-stack-remix
      POSTGRES_USER: demo-stack-remix
      POSTGRES_PASSWORD: demo-stack-remix
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
